dist: trusty
language: java
jdk:
  - oraclejdk8

script:
  - "./gradlew build"
after_success:
  - ".buildscript/deploy_snapshot.sh"

env:
  global:
    - secure: "A6U/C8pgjcJ+k2c/XIjtoaBsD+IydzJTHbYYMcJpJ6kritnFWbyCcRNl7UAHY4YYsFzwl9RRK11bFr9lzmt12+az94jBKoHTgkCmOnNKgGDV5WwEq2kV/wZFkzV4hslIR04B6Ea7mJtK7LeEVI7v/7YWdbj/d6Sj6VPpal8aB9am7+5nNgnweesQBE2/3X05rzlfDg8OIFmxo1V1Vgftr7x8z7yxjHs0bE1NHOvZ4V0VuaR+3ISLdEwz9SztUi3DDqw182qxFVMRE/lXt2YD4yc6MvaGC6qo6xmBPqKnds040wgvRzV50PIp0Gn+J8m8EHwLeDtUF5BOgiT+k2h+JX4D8IP7eu7LO9xNQVSg8cQ/Y9OGJe2CmaEJ8X0JcO4oUBcfDGMnOIK6ClQGT2wlO6hiO+XVO6OPKzm0AEwVB81rm9d4nF6WnzLzbBXMzteOvb8Zb94Zn7WQilbZbCuMiccE+/ffAK08NV7b6Txx62d/kLIdngkNM4zdVpjQT1qOA+omEx1CPiwLquHURtImj5lyvYsBwxfEXZU3eBaA/bx4cdEXAsrJ2XSgGnVbpjXTzJ1O+9ZcdXyE0uklvsmZVNngDPxBOvqZ9l3e2U6tXj1cx9ZmKGYdRvdcrQiMI9oa6diVJkRBDiGHIyvLHp3B7vCLBFEql1h0GRxQgE94iSo="
    - secure: "nDMl4+JsMtiyT3F8x4tIAaLpFVbxx7I/No7VqDH84NPdBVdx66hlyrcKF03CBjArgWskJPN05yWpWDAUyQOm7jaQIpTh2lDrlCzkscELz035h0B94LUderkKtM/CKQ0xnYJ4PTK7F+fEifUUOwqNi7nz6XlqGBMJCrtBOklKyluKjyihGDXnl18sAXFR7JhyOsm4jbc4Dn2n895x8M9BXU/uKTSjd4BzCjWBKmMxxhXB/u4hC2IfYT3MdVe+Uqvd/qjQ6zWXG/bhJkR94OlUsdBNlOS+RzGubgD9rJWjn3evU2Ol9hUfjTPtx1VjVe9Dt2O2Rgb742MZxzOx+/oPsN1locVvcCZztUTHQ0IpblJtWnB/9qOEwW84cB+Jhg4vrEjq+vidNEG5mXuaBQMgpkP+a+TIgv6/C6v/Ax8GBIcKrwdAoyFSkIN3CO+i3o2ICQ+5jH8pPXe2Ch6rfbC4G2WXXGYoeU5RQ8v+K9lFbXq2C9lw6M3u9BXIK1u0hTMv1ZplNCILJZWzpZ+eP1oA6IA1yMQIE3iU1QgqWc+75zVyIqPuH4omG1ZVfqCJc02X3W3+QcelrBqRBomJhYrj2CqtU+cX63fC7C7iZi5aRGwPyGeDUFgA2GNTdSDKj7pqvbvrKVBVASREj+np0plN7aiKZhENS3sRHfc0bT/MB+A="
branches:
  except:
    - gh-pages

notifications:
  email: false

cache:
  directories:
    - "$HOME/.gradle"
